### ISSUE TITLE
Not the latest version of GrafX2

### ISSUE THREAD

**Issue by pulkomandy** [xyproto/grafx2#561]
Hi,
GrafX2 is currently hosted at http://pulkomandy.tk/projects/GrafX2 / svn://pulkomandy.tk/GrafX2 . Please at least update your fork to the latest version.

**Comment by timofonic** [comment]
@pulkomandy 

I got the code by svn co URL. 

I'm unable to mirror it with svn2gitgub, the code is only available via the svn:// protocol. Can you allow http access in the server? Please :D

I found this one:
https://grafx2.googlecode.com/svn/
https://github.com/svn2github/GrafX2 (mirror)

What about putting it yourself?

PS: There's newschool people into pixel art, GrafX2 could get more attraction if promoted and some developers join the project :D

**Comment by pulkomandy** [comment]
You can use git-svn to manually mirror svn repo to git

https://git-scm.com/docs/git-svn

Then you can push to github.

**Comment by xyproto** [comment]
Checked that this fork is the latest version. Closing.

**Comment by pulkomandy** [comment]
GrafX2 upstream is now at gitlab: https://gitlab.com/GrafX2/grafX2/commits/master
I strongly suggest that you merge the 2 years of changes you are missing.

**Comment by xyproto** [comment]
Hi, the latest upstream changes does not work here (`sdl2` branch, which I assume is what almost everyone wants to use):

```
1.../grafx2/trunk% grafx2
Error in skin file: Was looking right from 254,139 for a 'mouse cursor', and reached the edge of the image
Error number 1 occured in file main.c, line 727, function Init_program.
Error: File containing the GUI graphics is missing!
This program cannot run without this file.
```

The application was installed on the system with `make install`, here is the current `PKGBUILD` file that I am testing with:

```bash
# $Id: PKGBUILD 176067 2016-05-21 17:05:53Z arodseth $
# Maintainer: Alexander F Rødseth <xyproto@archlinux.org>
# Contributor: Simon Parzer <simon.parzer@gmail.com>

pkgname=grafx2
pkgver=2.4
pkgrel=10
pkgdesc='Pixelart-oriented painting program'
arch=('x86_64' 'i686')
url='https://gitlab.com/GrafX2/grafx2'
license=('GPL2')
depends=('lua' 'fontconfig' 'sdl2_image' 'sdl2_ttf')
makedepends=('gendesk' 'git')
options=('!emptydirs')
source=("git+https://gitlab.com/GrafX2/grafX2.git#commit=e60d0179") # sdl2 branch
sha256sums=('SKIP')

prepare() {
  ln -sf "grafX2" "$pkgname"
  gendesk -f -n \
    --pkgname "$pkgname" \
    --pkgdesc "$pkgdesc" \
    --name 'GrafX2' \
    --genericname 'Drawing program' --exec 'grafx2 %f' \
    --mimetypes 'image/bmp;image/gif;image/png;image/x-tga;image/tiff' \
    --categories 'Graphics;2DGraphics;RasterGraphics'
}

build() {
  make -C "$pkgname/src"
}

package() {
  make -C "$pkgname/src" prefix=/usr DESTDIR="$pkgdir" install
  install -Dm644 "$pkgname.desktop" \
    "$pkgdir/usr/share/applications/$pkgname.desktop"
  install -Dm644 "$pkgname/doc/README.txt" \
    "$pkgdir/usr/share/doc/$pkgname/readme.txt"
}

# vim:set ts=2 sw=2 et:
```

If I can get the latest sdl2 branch from the gitlab repository to work, I would rather delete this fork here, since it was just meant to be used when the upstream webpage was down.

**Comment by pulkomandy** [comment]
The SDL2 branch is still work in progress, and the skin format has changed so it can't use an existing grafx2 settings directory (if you have a .grafx2 or .config/grafx2 in your home directory, that may be the problem).

I think it is better to use the master branch with SDL1.2 for now, until we are done with SDL2 developments.

**Comment by xyproto** [comment]
The error is still there after making sure `~/.grafx2` and `~/.config/grafx2` were gone before running the executable based on the latest commit in the `sdl2` branch.

The SDL1 version from master (commit cf56a349) works. I'll be using that one for the Arch Linux package, and will remove this repository (now that the gitlab repository is up).

Cheers!
